@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "Main.Menu#displayCharacter(Characters)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "Main.Menu",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1706344199 { 
   	label=Game
	labeljust=l
	fillcolor=white
	style=filled
   
   Game2390489XXXinit0[
	label="+ init()"
	style=filled
	fillcolor=white
	tooltip="Game

&#10;  Init methods calls methods which instantiate and define the character with it gears and attributes.&#10;  Allow to save and load characters&#10;  @throws SQLException&#10; "
	fontcolor=darkgreen
];

Game2390489XXXlaunch0[
	label="+ launch()"
	style=filled
	fillcolor=white
	tooltip="Game

&#10;  Launch methods defines the GameState (Enum) steps which define more precisely the proceedings&#10; &#10;  @throws PlayerOutOfBoundsException Sends an exception if the character overtake the table boarder&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1706522830 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main2390489XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1706526836 { 
   	label=Menu
	labeljust=l
	fillcolor=white
	style=filled
   
   Menu2390489XXXdisplayCharacter1056078198[
	label="+ displayCharacter()"
	style=filled
	fillcolor=white
	tooltip="Menu

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

'edges    
Game2390489XXXinit0 -> Menu2390489XXXdisplayCharacter1056078198;
Game2390489XXXlaunch0 -> Game2390489XXXinit0;
Main2390489XXXmain1859653459 -> Game2390489XXXlaunch0;
    
}
@enduml